### ISSUE TITLE
Add custom output formats

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2828]
See https://discuss.gohugo.io/t/custom-output-content-types/4584

Issues that this issue will also solve (will check):

* [x] Upper case tags #1641
* [x] Pagination links #2110 #2374 #1252
* [x] Ugly URL ambiguity #3102
* [x] Taxonomies vs ugly #1989 
* [x] Dots #1885 
* [x] Permalink for lang roots + ugly #3179
* [x] #320 configurable file ext
* [x] #2995 template lookup theme vs project

Other TODOS:

* [x] Rewrite pageLayoutIdentifier to use the descriptor/adapter pattern.
* [x] Handle`TODO(bep) output`
* [x] Rename `OutputType` => `OutputFormat`
* [x] Remove `siteWriter`.
* [x] Read Output formats from site config
* [x] Read Output format definitions from site config  => #3222
* [x] Read Media types from site config  => #3223
* [x] * Handle types in aliases
* [x] Add `Page.OutPutFormats` with `Permalink`, `RelPermalink` + a way to find `AMP` etc.
* [x] Base template handling
* [x] Partial handling
* [x] Text vs HTML templates => #3221
* [x] * Stats report
* [x] Ref vs relref => #3224
* [x] Register MIME types in server
* [x] * Handle protocol
* [x] * There is a panic in the themes site build with this branch.
* [x] Check injector + replacements vs suffix
